version: 2.1

references:
  python-versions: &python-versions ["3.6", "3.7", "3.8", "3.9"]

commands:
  install-python-dev-tools:
    steps:
      - run:
          name: Install python dev tools and dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends python3-pip
  poetry-install:
    parameters:
      dir:
        type: string
    steps:
      - install-python-dev-tools
      - run:
          name: install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            poetry config virtualenvs.in-project true
      - run:
          name: poetry install in << parameters.dir >>
          working_directory: << parameters.dir >>
          command: |
            poetry install

jobs:
  lint:
    docker:
      - image: python:3-buster
        auth: &docker-hub-auth
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - poetry-install:
          dir: compiler
      - poetry-install:
          dir: runtime
      - run:
          name: Lint onnion
          working_directory: compiler
          command: |
            poetry run pysen run lint
      - run:
          name: Lint onnion-rt
          working_directory: runtime
          command: |
            poetry run pysen run lint
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: python:<<parameters.python-version>>-buster
        auth: *docker-hub-auth
    steps:
      - checkout
      - poetry-install:
          dir: runtime
      - run:
          name: Test onnion-rt
          working_directory: runtime
          command: poetry run pytest -v

  test-by-examples:
    docker:
      - image: python:3-buster
        auth: &docker-hub-auth
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - poetry-install:
          dir: examples
      - run:
          name: check ultraface
          working_directory: examples
          command: |
            poetry run make -C ultraface check
      - run:
          name: check ssd
          working_directory: examples
          command: |
            poetry run make -C ssd check

  validate-version-with-tag:
    parameters:
      dir:
        type: string
      package-name:
        type: string
    docker:
      - image: python:3-buster
        auth: *docker-hub-auth
    steps:
      - checkout
      - poetry-install:
          dir: << parameters.dir >>
      - run:
          name: Check if git tag name is appropriate for package version
          working_directory: << parameters.dir >>
          command: |
            TAG=$(echo ${CIRCLE_TAG} |sed -e 's/<< parameters.package-name >>-//')
            VERSION=$(poetry run python -c 'import pkg_resources; print(pkg_resources.get_distribution("<< parameters.package-name >>").version)')
            echo "Git tag: $TAG"
            echo "Package version: $VERSION"
            test "$VERSION" = "$TAG"

  deploy-onnion:
    docker:
      - image: python:3-buster
        auth: *docker-hub-auth
    steps:
      - checkout
      - poetry-install:
          dir: compiler
      - run:
          name: Publish wheel & sdist to PyPI
          working_directory: compiler
          command: |
            poetry publish --build --username "__token__" --password "$PYPI_API_TOKEN_COMPILER" --no-interaction

  deploy-onnion-rt:
    docker:
      - image: python:3-buster
        auth: *docker-hub-auth
    steps:
      - checkout
      - poetry-install:
          dir: runtime
      - run:
          name: Publish wheel & sdist to PyPI
          working_directory: runtime
          command: |
            poetry publish --build --username "__token__" --password "$PYPI_API_TOKEN_RUNTIME" --no-interaction

workflows:
  version: 2
  commit:
    jobs:
      - lint:
          context:
            - docker-hub-creds
      - test:
          context:
            - docker-hub-creds
          matrix:
            parameters:
              python-version: *python-versions
      - test-by-examples:
          context:
            - docker-hub-creds

  release-onnion:
    jobs:
      - validate-version-with-tag:
          dir: compiler
          package-name: onnion
          context:
            - docker-hub-creds
          filters: &release-filter
            tags:
              only: /^onnion-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - deploy-onnion:
          context:
            - docker-hub-creds
          requires:
            - validate-version-with-tag
          filters: *release-filter

  release-onnion-rt:
    jobs:
      - validate-version-with-tag:
          dir: runtime
          package-name: onnion-rt
          context:
            - docker-hub-creds
          filters: &release-filter
            tags:
              only: /^onnion-rt-[0-9]+(\.[0-9]+){2}((a|b|rc)[0-9]+)?(.post[0-9])?(.dev[0-9])?$/
            branches:
              ignore: /.*/
      - deploy-onnion-rt:
          context:
            - docker-hub-creds
          requires:
            - validate-version-with-tag
          filters: *release-filter
